"""
PetCircle Phase 1 — Conflict Flag Model

Mirrors the 'conflict_flags' table exactly as defined in the frozen SQL schema.

Constraints:
    - preventive_record_id: FK to preventive_records(id), ON DELETE CASCADE
    - status: CHECK IN ('pending', 'resolved', 'auto_resolved')
    - new_date: the conflicting date extracted from a new document
    - Conflicts expire after CONFLICT_EXPIRY_DAYS (5 days) and auto-resolve
      with KEEP_EXISTING strategy — the new_date is discarded
"""

import uuid
from datetime import datetime, date
from sqlalchemy import Column, String, Date, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from app.database import Base


class ConflictFlag(Base):
    """
    Tracks a date conflict for a preventive record.

    Created when GPT extraction produces a date that differs from the
    existing last_done_date on a preventive record. The user must
    explicitly resolve the conflict via WhatsApp interactive buttons.

    Conflict lifecycle:
    - 'pending' — conflict detected, awaiting user decision
    - 'resolved' — user chose CONFLICT_USE_NEW or CONFLICT_KEEP_EXISTING
    - 'auto_resolved' — expired after CONFLICT_EXPIRY_DAYS (5 days),
      automatically resolved as KEEP_EXISTING, logged as system action

    No partial merge is allowed — it's all-or-nothing resolution.
    """

    __tablename__ = "conflict_flags"

    # Primary key — UUID generated by PostgreSQL (gen_random_uuid)
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Foreign key to preventive_records table.
    # ON DELETE CASCADE — removing the record removes its conflict flags.
    preventive_record_id = Column(
        UUID(as_uuid=True),
        ForeignKey("preventive_records.id", ondelete="CASCADE"),
    )

    # The new date extracted from a document that conflicts with existing data.
    # If resolved as USE_NEW, this date replaces last_done_date on the record.
    # If resolved as KEEP_EXISTING or auto-resolved, this date is discarded.
    new_date = Column(Date, nullable=False)

    # Conflict resolution status:
    # 'pending' — awaiting user decision via WhatsApp buttons
    # 'resolved' — user made an explicit choice
    # 'auto_resolved' — expired after 5 days, kept existing date
    status = Column(String(20), nullable=False)

    # Timestamp when the conflict was detected.
    created_at = Column(DateTime, default=datetime.utcnow)

    # --- Relationships ---

    # Back-reference to the preventive record this conflict belongs to.
    preventive_record = relationship("PreventiveRecord", back_populates="conflict_flags")
