"""
PetCircle Phase 1 — Dashboard Token Model

Mirrors the 'dashboard_tokens' table exactly as defined in the frozen SQL schema.

Constraints:
    - pet_id: FK to pets(id), ON DELETE CASCADE
    - token: UNIQUE, NOT NULL — 128-bit random hex string (32 characters)
    - revoked: soft revocation flag — revoked tokens are rejected at validation
    - Tokens are never physically deleted; revocation is a soft operation
"""

import uuid
from datetime import datetime
from sqlalchemy import Column, String, Boolean, DateTime, ForeignKey, Index
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from app.database import Base


class DashboardToken(Base):
    """
    Secure access token for the pet health dashboard.

    Generated as a 128-bit random hex string during onboarding completion.
    Sent to the user via WhatsApp template message as a shareable link.

    Tokens are validated on every dashboard access:
    - Must exist in the database
    - Must not be revoked (revoked=False)

    Revocation is soft delete only — the token row is kept for audit trail.
    Admin can revoke tokens via PATCH /admin/revoke-token/{pet_id}.
    """

    __tablename__ = "dashboard_tokens"

    # Primary key — UUID generated by PostgreSQL (gen_random_uuid)
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Foreign key to pets table.
    # ON DELETE CASCADE — removing a pet removes its dashboard token.
    pet_id = Column(UUID(as_uuid=True), ForeignKey("pets.id", ondelete="CASCADE"), index=True)

    # The actual token string — 128-bit random, rendered as 32-char hex.
    # UNIQUE constraint ensures no two tokens can collide.
    token = Column(String(255), unique=True, nullable=False)

    # Soft revocation flag — when True, the token is rejected at validation.
    # Tokens are never physically deleted to preserve audit trail.
    revoked = Column(Boolean, default=False)

    # Timestamp when the token expires.
    # Tokens older than this are rejected at validation.
    # Users can regenerate expired tokens by typing "dashboard" in WhatsApp.
    expires_at = Column(DateTime, nullable=False)

    # Timestamp when the token was generated.
    created_at = Column(DateTime, default=datetime.utcnow)

    # --- Relationships ---

    # Back-reference to the pet this token provides access to.
    pet = relationship("Pet", back_populates="dashboard_tokens")
