"""
PetCircle Phase 1 — Document Model

Mirrors the 'documents' table exactly as defined in the frozen SQL schema.

Constraints:
    - pet_id: FK to pets(id), ON DELETE CASCADE
    - extraction_status: CHECK IN ('pending', 'success', 'failed')
    - file_path: stores Supabase storage path ({user_id}/{pet_id}/{filename})
    - mime_type: validated against ALLOWED_MIME_TYPES at service layer
"""

import uuid
from datetime import datetime
from sqlalchemy import Column, String, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from app.database import Base


class Document(Base):
    """
    Represents an uploaded document (image or PDF) for a pet.

    Documents are stored in the private Supabase bucket at the path
    {user_id}/{pet_id}/{filename}. No public URLs are ever generated.

    After upload, GPT extraction processes the document to extract
    structured preventive health data. The extraction_status tracks
    this pipeline: pending → success/failed.
    """

    __tablename__ = "documents"

    # Primary key — UUID generated by PostgreSQL (gen_random_uuid)
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Foreign key to pets table.
    # ON DELETE CASCADE — removing a pet removes its documents.
    pet_id = Column(UUID(as_uuid=True), ForeignKey("pets.id", ondelete="CASCADE"), index=True)

    # Storage path in Supabase bucket: {user_id}/{pet_id}/{filename}.
    # Never contains public URLs — access is always through signed URLs.
    file_path = Column(String, nullable=False)

    # MIME type of the uploaded file.
    # Validated against ALLOWED_MIME_TYPES (image/jpeg, image/png, application/pdf)
    # at the service layer before insertion.
    mime_type = Column(String(50), nullable=False)

    # Human-readable document name classified by GPT during extraction.
    # Examples: "Blood Test Report", "Vaccination Certificate", "Deworming Record".
    # Set to None initially, populated after extraction completes.
    document_name = Column(String(200), nullable=True)

    # Document category assigned by GPT extraction.
    # Values: "Vaccination", "Prescription", "Diagnostic", "Other".
    # Used for grouping documents in the dashboard display.
    document_category = Column(String(30), nullable=True)

    # GPT extraction pipeline status:
    # 'pending' — uploaded, awaiting extraction
    # 'success' — extraction completed, structured data saved
    # 'failed' — extraction failed after retries, user notified
    extraction_status = Column(String(20), nullable=False)

    # WhatsApp message ID (wamid) that triggered this document upload.
    # Used for document-level deduplication — prevents phantom uploads
    # when Meta retries webhooks after server restarts or timeouts.
    # Unique constraint ensures one Document per WhatsApp message.
    source_wamid = Column(String(200), nullable=True, unique=True, index=True)

    # Timestamp when the document was uploaded.
    # Indexed for daily upload limit check queries.
    created_at = Column(DateTime, default=datetime.utcnow, index=True)

    # --- Relationships ---

    # Back-reference to the pet this document belongs to.
    pet = relationship("Pet", back_populates="documents")
