"""
PetCircle Phase 1 — Message Log Model

Mirrors the 'message_logs' table exactly as defined in the frozen SQL schema.

Constraints:
    - direction: CHECK IN ('incoming', 'outgoing')
    - payload: JSONB — stores the full message payload for audit trail
    - No foreign keys — message logs are standalone audit records
    - Logging must never block the main message processing flow
"""

import uuid
from datetime import datetime
from sqlalchemy import Column, String, DateTime
from sqlalchemy.dialects.postgresql import UUID, JSONB
from app.database import Base


class MessageLog(Base):
    """
    Audit log for all WhatsApp messages (incoming and outgoing).

    Every message passing through the system is logged here for
    debugging, compliance, and analytics. The payload column stores
    the complete message structure as JSONB.

    Logging failures must never block the main processing flow —
    they are caught and silently recorded where possible.
    """

    __tablename__ = "message_logs"

    # Primary key — UUID generated by PostgreSQL (gen_random_uuid)
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # WhatsApp mobile number associated with this message.
    # Not a foreign key — logs exist independently of user records.
    mobile_number = Column(String(15), nullable=True)

    # Message direction: 'incoming' (from user) or 'outgoing' (from system).
    direction = Column(String(10), nullable=True)

    # Type of message: 'text', 'image', 'document', 'button', 'template', etc.
    message_type = Column(String(20), nullable=True)

    # Full message payload stored as JSONB for complete audit trail.
    # Includes all metadata, timestamps, and content from WhatsApp.
    payload = Column(JSONB, nullable=True)

    # WhatsApp message ID (wamid) from Meta — used for persistent deduplication.
    # Partial unique index ensures duplicates are rejected at the DB level
    # while allowing NULL for old rows and outgoing messages.
    wamid = Column(String(200), nullable=True, unique=True, index=True)

    # Timestamp when the log entry was created.
    # Indexed for admin panel queries that order by created_at desc.
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
