"""
PetCircle — Order Model

Mirrors the 'orders' table for lightweight product order requests via WhatsApp.
Orders are not e-commerce transactions — admin receives a notification and
calls the user to process the order manually.

Constraints:
    - user_id: FK to users(id), ON DELETE CASCADE
    - pet_id: FK to pets(id), ON DELETE SET NULL (nullable — pet may not be specified)
    - category: medicines, food_nutrition, supplements
    - status: pending, confirmed, completed, cancelled
    - items_description: free text up to 2000 chars
"""

import uuid
from datetime import datetime
from sqlalchemy import Column, String, DateTime, ForeignKey, Index
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from app.database import Base


class Order(Base):
    """
    Represents a product order request submitted via WhatsApp.

    Orders go through a simple lifecycle: pending → confirmed → completed.
    Admin processes orders manually by calling the user.
    """

    __tablename__ = "orders"

    # Primary key — UUID generated by PostgreSQL (gen_random_uuid)
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Foreign key to users table.
    # ON DELETE CASCADE — if user is physically deleted, orders are removed.
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Foreign key to pets table — nullable because user may not have selected a pet yet
    # (draft state) or may have no pets registered.
    # ON DELETE SET NULL — if pet is deleted, order remains but loses pet reference.
    pet_id = Column(
        UUID(as_uuid=True),
        ForeignKey("pets.id", ondelete="SET NULL"),
        nullable=True,
    )

    # Order category — one of: medicines, food_nutrition, supplements.
    category = Column(String(30), nullable=False)

    # Free-text description of items the user wants to order.
    items_description = Column(String(2000), nullable=False)

    # Order status lifecycle: pending → confirmed → completed (or cancelled at any point).
    status = Column(String(20), nullable=False, default="pending")

    # Admin notes — free text added by admin when processing the order.
    admin_notes = Column(String(2000), nullable=True)

    # Timestamps managed by PostgreSQL DEFAULT NOW().
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # --- Indexes ---
    __table_args__ = (
        Index("ix_orders_status", "status"),
        Index("ix_orders_created_at", "created_at"),
    )

    # --- Relationships ---

    # Back-reference to the owning user.
    user = relationship("User", back_populates="orders", foreign_keys=[user_id])

    # Back-reference to the pet (optional).
    pet = relationship("Pet", back_populates="orders")
