"""
PetCircle Phase 1 — Pet Model

Mirrors the 'pets' table exactly as defined in the frozen SQL schema.

Constraints:
    - user_id: FK to users(id), ON DELETE CASCADE
    - species: CHECK IN ('dog', 'cat') — only these two supported in Phase 1
    - gender: CHECK IN ('male', 'female')
    - weight: DECIMAL(5,2) — supports up to 999.99 kg
    - is_deleted: soft delete flag — physical deletes are never performed
    - Max 5 pets per user enforced at service layer (not DB constraint)
"""

import uuid
from datetime import datetime, date
from decimal import Decimal
from sqlalchemy import Column, String, Boolean, DateTime, Date, Numeric, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from app.database import Base


class Pet(Base):
    """
    Represents a pet registered under a user account.

    Species is restricted to 'dog' or 'cat'.
    Soft delete via is_deleted flag; physical delete is never used.
    The 5-pet-per-user limit is enforced in the service layer, not here.
    """

    __tablename__ = "pets"

    # Primary key — UUID generated by PostgreSQL (gen_random_uuid)
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Foreign key to users table.
    # ON DELETE CASCADE — if user is physically deleted, pets are removed.
    # However, soft delete is the standard practice; cascade is a safety net.
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"))

    # Pet name collected during onboarding.
    name = Column(String(100), nullable=False)

    # Species — restricted to 'dog' or 'cat' via CHECK constraint.
    # This determines which preventive_master items apply to this pet.
    species = Column(String(10), nullable=False)

    # Breed — optional, free text.
    breed = Column(String(100), nullable=True)

    # Gender — restricted to 'male' or 'female' via CHECK constraint.
    gender = Column(String(10), nullable=True)

    # Date of birth — used for age-based preventive scheduling.
    dob = Column(Date, nullable=True)

    # Weight in kg — DECIMAL(5,2) allows up to 999.99.
    weight = Column(Numeric(5, 2), nullable=True)

    # Neutered status — relevant for certain health recommendations.
    neutered = Column(Boolean, nullable=True)

    # Weight flagged — True when AI deems weight unusual for breed/age
    # and user confirmed it anyway during onboarding. Shown in red on dashboard.
    weight_flagged = Column(Boolean, default=False)

    # Soft delete flag — when True, pet is treated as deleted.
    is_deleted = Column(Boolean, default=False)

    # Timestamps managed by PostgreSQL DEFAULT NOW().
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # --- Relationships ---

    # Back-reference to the owning user.
    user = relationship("User", back_populates="pets")

    # One pet can have many preventive records.
    preventive_records = relationship("PreventiveRecord", back_populates="pet")

    # One pet can have many uploaded documents.
    documents = relationship("Document", back_populates="pet")

    # One pet has one dashboard token (but modeled as relationship for flexibility).
    dashboard_tokens = relationship("DashboardToken", back_populates="pet")
