"""
PetCircle Phase 1 — Preventive Master Model

Mirrors the 'preventive_master' table exactly as defined in the frozen SQL schema.
This table is seeded once and never modified at runtime.

Constraints:
    - category: CHECK IN ('essential', 'complete')
    - circle: CHECK IN ('health', 'nutrition', 'hygiene')
    - species: CHECK IN ('dog', 'cat', 'both')
    - UNIQUE(item_name, species) — prevents duplicate entries per species
    - recurrence_days: determines the interval for next_due_date calculation
    - This table is frozen — always read from DB, no fallback values in code
"""

import uuid
from sqlalchemy import Column, String, Integer, Boolean, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from app.database import Base


class PreventiveMaster(Base):
    """
    Reference table defining all preventive health items.

    This table is seeded from the frozen preventive master list (Module 6)
    and never modified during runtime. All preventive logic reads from this
    table — recurrence intervals are never hardcoded in application code.

    The UNIQUE(item_name, species) constraint ensures no duplicate items
    exist for the same species.
    """

    __tablename__ = "preventive_master"

    # Primary key — UUID generated by PostgreSQL (gen_random_uuid)
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Name of the preventive health item (e.g., "Rabies Vaccine", "Deworming").
    item_name = Column(String(120), nullable=False)

    # Category determines health score weighting:
    # 'essential' items have 0.9 weight, 'complete' items have 0.1 weight.
    # CHECK constraint enforces only 'essential' or 'complete'.
    category = Column(String(20), nullable=False)

    # Dashboard ring grouping: 'health', 'nutrition', or 'hygiene'.
    # Determines which concentric Activity Ring this item contributes to.
    circle = Column(String(20), nullable=False, server_default="health")

    # Species this item applies to: 'dog', 'cat', or 'both'.
    # Used to filter applicable items when creating preventive records for a pet.
    species = Column(String(10), nullable=False)

    # Number of days between occurrences.
    # Used by preventive calculator: next_due_date = last_done_date + recurrence_days.
    # Always read from this table — never hardcoded in application code.
    recurrence_days = Column(Integer, nullable=False)

    # Whether this item depends on a specific medicine/product.
    medicine_dependent = Column(Boolean, default=False)

    # How many days before next_due_date to send the first reminder.
    reminder_before_days = Column(Integer, nullable=False)

    # How many days after next_due_date before marking as overdue.
    overdue_after_days = Column(Integer, nullable=False)

    # --- Unique Constraint ---
    # Prevents duplicate preventive items for the same species.
    # e.g., only one "Rabies Vaccine" entry for "dog".
    __table_args__ = (
        UniqueConstraint("item_name", "species", name="uq_preventive_master_item_species"),
    )

    # Relationship to preventive records that reference this master item.
    preventive_records = relationship("PreventiveRecord", back_populates="preventive_master")
