"""
PetCircle Phase 1 — Preventive Record Model

Mirrors the 'preventive_records' table exactly as defined in the frozen SQL schema.

Constraints:
    - pet_id: FK to pets(id), ON DELETE CASCADE
    - preventive_master_id: FK to preventive_master(id)
    - status: CHECK IN ('up_to_date', 'upcoming', 'overdue', 'cancelled')
    - UNIQUE(pet_id, preventive_master_id, last_done_date) — prevents duplicate
      records for the same pet, preventive item, and date. This is the core
      idempotency protection for the preventive system.
"""

import uuid
from datetime import datetime, date
from sqlalchemy import Column, String, Date, DateTime, ForeignKey, UniqueConstraint, Index
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from app.database import Base


class PreventiveRecord(Base):
    """
    Tracks a specific preventive health event for a pet.

    Each record links a pet to a preventive master item with a specific
    last_done_date and computed next_due_date. Status is recalculated
    by the preventive calculator based on current date vs next_due_date.

    The UNIQUE(pet_id, preventive_master_id, last_done_date) constraint
    ensures idempotency — the same preventive event cannot be recorded twice.
    """

    __tablename__ = "preventive_records"

    # Primary key — UUID generated by PostgreSQL (gen_random_uuid)
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Foreign key to pets table.
    # ON DELETE CASCADE — removing a pet removes its preventive records.
    pet_id = Column(UUID(as_uuid=True), ForeignKey("pets.id", ondelete="CASCADE"), index=True)

    # Foreign key to preventive_master table.
    # Links this record to a specific preventive item (e.g., Rabies Vaccine).
    preventive_master_id = Column(UUID(as_uuid=True), ForeignKey("preventive_master.id"))

    # Date the preventive action was last performed.
    # Nullable for newly onboarded pets that have no prior records yet.
    last_done_date = Column(Date, nullable=True)

    # Computed next due date: last_done_date + preventive_master.recurrence_days.
    # Recalculated whenever last_done_date changes.
    # Nullable when last_done_date is not yet known.
    next_due_date = Column(Date, nullable=True)

    # Current status based on date comparison:
    # 'up_to_date' — next_due_date is far enough away
    # 'upcoming' — within reminder_before_days of next_due_date
    # 'overdue' — past next_due_date
    # 'cancelled' — user explicitly cancelled this preventive item
    status = Column(String(20), nullable=False)

    # Timestamps managed by PostgreSQL DEFAULT NOW().
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # --- Unique Constraint ---
    # Idempotency protection: prevents recording the same preventive event
    # for the same pet on the same date twice. Critical for deduplication
    # when GPT extraction or user input is retried.
    __table_args__ = (
        UniqueConstraint(
            "pet_id", "preventive_master_id", "last_done_date",
            name="uq_preventive_record_pet_item_date"
        ),
        # Composite index for reminder engine queries filtering by pet + status.
        Index("ix_preventive_record_pet_status", "pet_id", "status"),
    )

    # --- Relationships ---

    # Back-reference to the pet this record belongs to.
    pet = relationship("Pet", back_populates="preventive_records")

    # Back-reference to the preventive master item.
    preventive_master = relationship("PreventiveMaster", back_populates="preventive_records")

    # One preventive record can have many reminders (one per next_due_date cycle).
    reminders = relationship("Reminder", back_populates="preventive_record")

    # One preventive record can have conflict flags if extracted dates differ.
    conflict_flags = relationship("ConflictFlag", back_populates="preventive_record")
