"""
PetCircle Phase 1 — Reminder Model

Mirrors the 'reminders' table exactly as defined in the frozen SQL schema.

Constraints:
    - preventive_record_id: FK to preventive_records(id), ON DELETE CASCADE
    - status: CHECK IN ('pending', 'sent', 'completed', 'snoozed')
    - UNIQUE(preventive_record_id, next_due_date) — deduplication constraint
      ensures only one reminder exists per preventive record per due date cycle.
      This is critical for the stateless reminder engine (Module 10) which runs
      daily and must not create duplicate reminders.
"""

import uuid
from datetime import datetime, date
from sqlalchemy import Column, String, Date, DateTime, ForeignKey, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from app.database import Base


class Reminder(Base):
    """
    Tracks a reminder sent for a specific preventive record's due date.

    The reminder engine (cron at 8 AM IST) creates reminders for records
    approaching their next_due_date. The UNIQUE constraint on
    (preventive_record_id, next_due_date) prevents the stateless cron
    from creating duplicates across runs.

    Status lifecycle: pending → sent → completed/snoozed
    """

    __tablename__ = "reminders"

    # Primary key — UUID generated by PostgreSQL (gen_random_uuid)
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Foreign key to preventive_records table.
    # ON DELETE CASCADE — removing a preventive record removes its reminders.
    preventive_record_id = Column(
        UUID(as_uuid=True),
        ForeignKey("preventive_records.id", ondelete="CASCADE"),
    )

    # The due date this reminder is for.
    # Stored separately because next_due_date on the record can change
    # (e.g., snooze), and we need to track which cycle this reminder belongs to.
    next_due_date = Column(Date, nullable=False)

    # Reminder status:
    # 'pending' — created but not yet sent
    # 'sent' — WhatsApp template message delivered
    # 'completed' — user responded REMINDER_DONE
    # 'snoozed' — user responded REMINDER_SNOOZE_7
    status = Column(String(20), nullable=False)

    # Timestamp when the WhatsApp reminder was actually sent.
    # NULL until status transitions to 'sent'.
    sent_at = Column(DateTime, nullable=True)

    # Timestamp when the reminder was created.
    created_at = Column(DateTime, default=datetime.utcnow)

    # --- Unique Constraint ---
    # Deduplication: only one reminder per preventive record per due date.
    # The reminder engine is stateless and runs daily — this constraint
    # prevents it from creating duplicate reminders on repeated runs.
    __table_args__ = (
        UniqueConstraint(
            "preventive_record_id", "next_due_date",
            name="uq_reminder_record_duedate"
        ),
    )

    # --- Relationships ---

    # Back-reference to the preventive record this reminder belongs to.
    preventive_record = relationship("PreventiveRecord", back_populates="reminders")
