"""
PetCircle Phase 1 — User Model

Mirrors the 'users' table exactly as defined in the frozen SQL schema.
Mobile number serves as the unique identifier for WhatsApp-based authentication.

Constraints:
    - mobile_number: UNIQUE, NOT NULL — one account per WhatsApp number
    - is_deleted: soft delete flag — physical deletes are never performed
    - Cascade: deleting a user cascades to pets (defined on pets FK side)
"""

import uuid
from datetime import datetime
from sqlalchemy import Column, String, Boolean, DateTime
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from app.database import Base


class User(Base):
    """
    Represents a pet parent registered via WhatsApp.

    Mobile number is the unique identifier — no email or password auth in Phase 1.
    Soft delete via is_deleted flag; physical delete is never used.
    """

    __tablename__ = "users"

    # Primary key — UUID generated by PostgreSQL (gen_random_uuid)
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # WhatsApp mobile number — unique identifier for the user.
    # VARCHAR(15) accommodates international formats with country code.
    mobile_number = Column(String(15), unique=True, nullable=False)

    # Full name collected during onboarding.
    full_name = Column(String(120), nullable=False)

    # Indian pincode for location context.
    pincode = Column(String(10), nullable=True)

    # Email address — optional, used to send dashboard links.
    email = Column(String(255), nullable=True)

    # Consent flag — True once user has accepted terms.
    # Timestamp of consent is the created_at when consent_given=True.
    consent_given = Column(Boolean, default=False)

    # Onboarding state — tracks multi-step WhatsApp conversation.
    # States: awaiting_consent, awaiting_name, awaiting_pincode,
    #         awaiting_pet_name, awaiting_species, awaiting_breed,
    #         awaiting_gender, awaiting_dob, awaiting_weight,
    #         awaiting_neutered, complete
    onboarding_state = Column(String(30), default="awaiting_consent")

    # Soft delete flag — when True, user is treated as deleted.
    # No physical delete is ever performed; this preserves audit trail.
    is_deleted = Column(Boolean, default=False)

    # Timestamps managed by PostgreSQL DEFAULT NOW().
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationship to pets — one user can have up to MAX_PETS_PER_USER pets.
    # Cascade defined on the Pet model's foreign key side.
    pets = relationship("Pet", back_populates="user")
